### ISSUE TITLE
Refactoring for VirtualRental

### ISSUE THREAD

**Issue by designe** [designe/VirtualRental10#1]
* Cmd로부터 DB API 분리 -> Database 클래스를 새로 만들어서 관련 없는걸 분리 하면 좋을 듯
https://github.com/designe/VirtualRental10/blob/35f0527990862894bd6508e842bf193f64df4e1e/src/main/java/video/rental/demo/CmdUI.java#L269

* 아래와 같은 입출력에 관한 부분을 비즈니스 로직으로부터 분리한다
https://github.com/designe/VirtualRental10/blob/35f0527990862894bd6508e842bf193f64df4e1e/src/main/java/video/rental/demo/CmdUI.java#L60

```java
	public void clearRentals(int customerCode) { // 입출력을 모두 제거하고 argument로 받을 수 있게 변경
		//System.out.println("Enter customer code: ");
		//int customerCode = scanner.nextInt();

		Customer foundCustomer = findCustomerById(customerCode);

		if (foundCustomer == null) {
			//System.out.println("No customer found");
                        // -> return 0
		} else {
			//System.out.println("Id: " + foundCustomer.getCode() + "\nName: " + foundCustomer.getName() + "\tRentals: "
					+ foundCustomer.getRentals().size());
                        // return foundCustomer로 변경해서 UI 부분과 로직을 완전분리하면 좋을 듯
			for (Rental rental : foundCustomer.getRentals()) {
				System.out.print("\tTitle: " + rental.getVideo().getTitle() + " ");
				System.out.print("\tPrice Code: " + rental.getVideo().getPriceCode());
			}

			List<Rental> rentals = new ArrayList<Rental>();
			foundCustomer.setRentals(rentals);

			saveCustomer(foundCustomer);
		}
	}
```

* GUI 코드에서는 전부 출력을 textArea.append 이걸로 하는데 CUI에서는 system.out.println 으로 하는게 차이점이네요
https://github.com/designe/VirtualRental10/blob/35f0527990862894bd6508e842bf193f64df4e1e/src/main/java/video/rental/demo/GraphicUI.java#L177

**Comment by bethebiggreen** [comment]
-  GUI 연동을 위해서는 UI 의 실시간성이 보장되어야 한다. 하지만, 현재 start() 함수가 메인컨텍스트에서 while loop 를 종료때 까지 수행하고, 각 명령 처리들은 Synchronous 구현되어 있다.
-  GUI 지원으로 바꾸기 위해서는, UI thread 를 메인쓰레드로 분리하고, 각 명령을 처리하는 쓰레드를 복수로 드는 멀티쓰레드 프로그래밍이 필요햐다.

**Comment by ace772** [comment]
switch (command) {

**Comment by ace772** [comment]
VirtualRental10/src/main/java/video/rental/demo/CmdUI.java

Line 22 in 35f0527

 while (!quit) {  
		switch (command) {

**Comment by ace772** [comment]
* 아래 DB관련 함수 4개는 다른 클래스로 빼는것이 좋아 보임 

* 클리어 렌탈함수는 클리어를 하면서 고객정보를 출력하고 있다. 하나의 역할만 하는것이 좋아 보임 

public void clearRentals() {
		System.out.println("Enter customer code: ");
		int customerCode = scanner.nextInt();
		Customer foundCustomer = findCustomerById(customerCode);

		if (foundCustomer == null) {
			System.out.println("No customer found");
		} else {
			System.out.println("Id: " + foundCustomer.getCode() + "\nName: " + foundCustomer.getName() + "\tRentals: "
					+ foundCustomer.getRentals().size());
			for (Rental rental : foundCustomer.getRentals()) {
				System.out.print("\tTitle: " + rental.getVideo().getTitle() + " ");
				System.out.print("\tPrice Code: " + rental.getVideo().getPriceCode());
			}

			List<Rental> rentals = new ArrayList<Rental>();
			foundCustomer.setRentals(rentals);

			saveCustomer(foundCustomer);
		}
	}
