### ISSUE TITLE
Switch문보다는 각각의 객체로 이양하는것이 좋아보임.

### ISSUE THREAD

**Issue by ace772** [designe/VirtualRental10#2]
https://github.com/designe/VirtualRental10/blob/35f0527990862894bd6508e842bf193f64df4e1e/src/main/java/video/rental/demo/CmdUI.java#L22

**Comment by designe** [comment]
https://github.com/designe/VirtualRental10/blob/35f0527990862894bd6508e842bf193f64df4e1e/src/main/java/video/rental/demo/Video.java#L48

요게 VideoType에 따라 switch 분기가 꽤 많이 들어가는데 요것도 전부 Video 타입별로 뽑아서 state pattern 하면 좋을 것 같아요
